### Importing libraries

In [1]:
import numpy as np
import random
from sklearn.model_selection import train_test_split
import json
from sklearn.feature_extraction.text import CountVectorizer

### Creating data classes

In [2]:
class Sentiment:
    Negative = 'NEGATIVE'
    Neutral = 'NEUTRAL'
    Positive = 'POSITIVE'
    

In [3]:
class Review:
    def __init__(self, text, score):
        self.text = text
        self.score = score
        self.sentiment = self.get_sentiment()
        
    def get_sentiment(self):
        if self.score <= 2:
            return Sentiment.Negative
        elif self.score ==3:
            return Sentiment.Neutral
        else:
            return Sentiment.Positive

### Loading data

In [4]:
file_name = 'Books_small_10000.json' #Changed the previous books_small.json data set to Books_small_10000.json data set to fix the data imbalance

reviews = []
with open(file_name) as f:
    for line in f:
        review = json.loads(line)
        reviews.append(Review(review['reviewText'], review['overall']))
        
        
reviews[5].text

'I hoped for Mia to have some peace in this book, but her story is so real and raw.  Broken World was so touching and emotional because you go from Mia\'s trauma to her trying to cope.  I love the way the story displays how there is no "just bouncing back" from being sexually assaulted.  Mia showed us how those demons come for you every day and how sometimes they best you. I was so in the moment with Broken World and hurt with Mia because she was surrounded by people but so alone and I understood her feelings.  I found myself wishing I could give her some of my courage and strength or even just to be there for her.  Thank you Lizzy for putting a great character\'s voice on a strong subject and making it so that other peoples story may be heard through Mia\'s.'

### Splitting data into train and test

In [5]:
train, test = train_test_split(reviews, test_size=0.3, random_state=42)

In [6]:
print(train[0].sentiment)

NEUTRAL


### Seperating text data and sentiment score data

In [7]:
x_train = [x.text for x in train]
y_train = [x.sentiment for x in train]

y_train

['NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEUTRAL',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSIT

In [8]:
x_train[0]

"I had to think long and hard about what I wanted to write for my review.  The author makes a point several times in her book to say that it is easier to criticize then be uplifting and happy.However I will start with a little criticism and finish with happy.  I found that author to be a generally negative person who portrays herself as someone who snaps at people a lot of generally has a negative, or critical attitude.  Those things really put me off from the book and at times I wondered why I was punishing myself to finish the book.However I did glean several things from it:1) a recommendation of the next book I want to read &#34;The Story of a Soul&#34;2) I learned that hugging for 6 seconds is the minimum to gain the positive effects from the action3) To remember that the years are short4) Enjoy the present5) Portraying yourself as happy can indeed make you happierI don't want to continue for it might spoil the rest of the book.I struggled with whether to say I would recommend this

In [9]:
y_train[0]

'NEUTRAL'

In [10]:
x_test = [x.text for x in test]
y_test = [x.sentiment for x in test]

y_test

['POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'POSITIVE',
 'NEUTRAL',
 'PO

### Bag of words concept: using count vectorizer to transform text data into a format that the model can understand

In [11]:
#Using count vectorizer to transform text data
vectorizer = CountVectorizer()

x_train_vec = vectorizer.fit_transform(x_train)

x_test_vectors = vectorizer.transform(x_test)

### Building our models

### Support Vector Machine

In [12]:
#Svm classifier
from sklearn import svm

In [13]:
clf_svm = svm.SVC(kernel='linear')

In [14]:
clf_svm.fit(x_train_vec, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
x_test[0]

"was sent an Arc of this book for an honest review and here it is = This is the kind of book that you want to read while sitting in front of the fire with a cup of hot apple cider and a blanket over your legs.I have read many of Jaci Burton's books and have never been disappointed. This first book in her new Hope series does not disappoint either.This is the story of Emma, a new vet who has come back home to open her own practice and Luke McCormack, a police officer in the same town.Both have been previously burned by love so both have issues but, that doesn't stop them from acting on that attraction.This book pulls you in from the first page, wraps you up and doesn't let you go until the end.I loved it!"

In [16]:
clf_svm.predict(x_test_vectors)

array(['POSITIVE', 'POSITIVE', 'POSITIVE', ..., 'POSITIVE', 'POSITIVE',
       'POSITIVE'], dtype='<U8')

### Decision Tree

In [17]:
#Decision tree classifier
from sklearn.tree import DecisionTreeClassifier

In [18]:
dt_clf = DecisionTreeClassifier()

dt_clf.fit(x_train_vec, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [19]:
dt_clf.predict(x_test_vectors[0])

array(['POSITIVE'], dtype='<U8')

### Logistic Regression

In [20]:
#Logistic regression classifier
from sklearn.linear_model import LogisticRegression

In [21]:
log_clf = LogisticRegression(max_iter=1000)

log_clf.fit(x_train_vec, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
log_clf.predict(x_test_vectors[0])

array(['POSITIVE'], dtype='<U8')

### Random Forest

In [23]:
#Random forest classifier
from sklearn.ensemble import RandomForestClassifier

In [24]:
rf_clf = RandomForestClassifier()

rf_clf.fit(x_train_vec, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [25]:
rf_clf.predict(x_test_vectors[0])

array(['POSITIVE'], dtype='<U8')

### Evaluation

### Mean accuracy

In [26]:
print(" The mean accuracy score of the svm classifier: {}".format(clf_svm.score(x_test_vectors, y_test)))
print(" The mean accuracy score of the decision tree classifier: {}".format(dt_clf.score(x_test_vectors, y_test)))
print(" The mean accuracy score of the logistic regression classifier: {}".format(log_clf.score(x_test_vectors, y_test)))
print(" The mean accuracy score of the random forest classifier: {}".format(rf_clf.score(x_test_vectors, y_test)))













 The mean accuracy score of the svm classifier: 0.814
 The mean accuracy score of the decision tree classifier: 0.7773333333333333
 The mean accuracy score of the logistic regression classifier: 0.8453333333333334
 The mean accuracy score of the random forest classifier: 0.8413333333333334


### F1 score

In [27]:
from sklearn.metrics import f1_score

In [28]:
#Svm classifier
f1_score(y_test, clf_svm.predict(x_test_vectors), average=None, labels=[Sentiment.Positive,Sentiment.Negative])

array([0.90807799, 0.41293532])

In [29]:
#Decision tree classifier
f1_score(y_test, dt_clf.predict(x_test_vectors), average=None, labels=[Sentiment.Positive,Sentiment.Negative])

array([0.88020324, 0.1994302 ])

In [30]:
#Logistic regression classifier
f1_score(y_test, log_clf.predict(x_test_vectors), average=None, labels=[Sentiment.Positive,Sentiment.Negative])

array([0.92298784, 0.44728435])

In [31]:
#Random forest classifier
f1_score(y_test, rf_clf.predict(x_test_vectors), average=None, labels=[Sentiment.Positive,Sentiment.Negative])

array([0.91383056, 0.        ])

In [32]:
y_train.count(Sentiment.Positive)

5854

In [33]:
y_train.count(Sentiment.Negative)

461

### Report.
- Our model was biased to positive reviews because the data set was imbalanced with 577 positive reviews to 48 negative reviews.

- To change that we will increase the size of our data set to 10,000 reviews to offset the imbalance 

In [38]:
test_set = ['The  book had a poor storyline, i did not enjoy', 'Bad book do not buy', 'A horrible waste of time']

new_test = vectorizer.transform(test_set)

log_clf.predict(new_test)

array(['POSITIVE', 'POSITIVE', 'NEGATIVE', 'NEGATIVE'], dtype='<U8')